import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({ subsets: ['latin'], weight: ["400", "500", "600", "700"] })

export const metadata = {
    title: 'Components',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" className='overflow-hidden cursor-none'>
            <body className={poppins.className}>{children}</body>
        </html>
    )
}
